theme = "zed_onedark" 

[editor]
line-number = "relative"
auto-save = true
auto-completion = true
clipboard-provider = "x-clip"
continue-comments = true
auto-info = true
rulers = [100]
cursorline = true
bufferline = "always"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.file-picker]
hidden = true

[keys.normal]
"A-s" = ":write"
"A-." = ":bnext"
"A-," = ":bprev"
"A-c" = ":buffer-close"
"A-C" = ":buffer-close-others"


[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal.space]
"q" = ":quit"
"Q" = ":quit!"

